remote_theme: "dracula/gh-pages"
title: "Känguru-Soundboard"
description: "Coole Sprüche/Sounds aus den Känguru-Chroniken."
show_header: false
colorspace: red
icon: icon.svg
kramdown:
  auto_ids: true