name: Deploy to GitHub Pages
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build
              run: |
                mkdir build
                python3 build.py

            - name: Create feed.rss
              run: |
                python3 rss/createfeeds.py
                cp feed.rss build/feed.rss
            - name: Copy files
              run: |
                cp -r files build/files
                cp _config.yml build/

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:

                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: build
                  enable_jekyll: true
