name: Deploy to GitHub Pages
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build
              run: |
                mkdir build
                python3 build.py

            - name: Copy files
              run: |
                cp -r files build/files
                echo "theme: jekyll-theme-midnight" > build/_config.yml

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: build
